import 'package:htimer_app/model/timer_data.dart';
import 'package:flutter/material.dart';
import 'package:htimer_app/data/exercise_data.dart';
import 'package:htimer_app/constants.dart';

TimerData get day1 => TimerData(
      timerName: 'Jump Rope Calisthenics',
      timerType: TimerType.tabata,
      sets: 1,
      exerciseCount: 10,
      startDelay: Duration(seconds: 5),
      restIntervals: Duration(seconds: 10),
      restSets: Duration(seconds: 0),
      exerciseDetailList: [
        ExerciseDetails(
          name: 'Jump Rope Feet Side to Side',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'High Knees',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Feet Front to Back',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Speed Skaters',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Butt Kicks',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Regular Bounce',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jumping Jacks',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Fast Skip',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Plank',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
      ],
      colorSetRest: Colors.deepOrange,
      colorInterval: Colors.blueGrey,
      colorCountDown: Colors.teal,
      randomise: false,
      tabataStyle: false,
      vibrate: false,
      alertName: alertList[2],
    );

TimerData get day2 => TimerData(
      timerName: 'Jump Rope & Upper Body',
      timerType: TimerType.tabata,
      sets: 1,
      exerciseCount: 6,
      startDelay: Duration(seconds: 5),
      restIntervals: Duration(seconds: 30),
      restSets: Duration(seconds: 0),
      exerciseDetailList: [
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(minutes: 1),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: '20 Regular Push Ups',
          duration: Duration(minutes: 1),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(minutes: 1),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Plank',
          duration: Duration(minutes: 1),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(minutes: 1),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: '20 Tricep Push Ups',
          duration: Duration(minutes: 1),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
      ],
      colorSetRest: Colors.deepOrange,
      colorInterval: Colors.blueGrey,
      colorCountDown: Colors.teal,
      randomise: false,
      tabataStyle: false,
      vibrate: false,
      alertName: alertList[2],
    );

TimerData get day3 => TimerData(
      timerName: 'Jump Rope & Core Body',
      timerType: TimerType.tabata,
      sets: 1,
      exerciseCount: 8,
      startDelay: Duration(seconds: 5),
      restIntervals: Duration(seconds: 10),
      restSets: Duration(seconds: 0),
      exerciseDetailList: [
        ExerciseDetails(
          name: 'Jump Rope Freestyle',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Plank Jacks',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Feet Front to Back',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Abs Crunchers',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Feet Side to Side',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Leg Raise (Hold for 30 Sec)',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Feet Front to Back',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Plank',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
      ],
      colorSetRest: Colors.deepOrange,
      colorInterval: Colors.blueGrey,
      colorCountDown: Colors.teal,
      randomise: false,
      tabataStyle: false,
      vibrate: false,
      alertName: alertList[2],
    );

TimerData get day4 => TimerData(
      timerName: 'Jump Rope & Lower Body',
      timerType: TimerType.tabata,
      sets: 1,
      exerciseCount: 8,
      startDelay: Duration(seconds: 5),
      restIntervals: Duration(seconds: 10),
      restSets: Duration(seconds: 0),
      exerciseDetailList: [
        ExerciseDetails(
          name: 'Jump Rope Regular Bounce',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Air Squats',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Feet X\'S',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Front Lunges',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Squats',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Regular Bounce',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jumping Lunges',
          duration: Duration(seconds: 30),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
      ],
      colorSetRest: Colors.deepOrange,
      colorInterval: Colors.blueGrey,
      colorCountDown: Colors.teal,
      randomise: false,
      tabataStyle: false,
      vibrate: false,
      alertName: alertList[2],
    );

TimerData get day5 => TimerData(
      timerName: 'Jump Rope Tabata',
      timerType: TimerType.tabata,
      sets: 1,
      exerciseCount: 8,
      startDelay: Duration(seconds: 5),
      restIntervals: Duration(seconds: 10),
      restSets: Duration(seconds: 0),
      exerciseDetailList: [
        ExerciseDetails(
          name: 'Jump Rope Regular Bounce',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Run in Place ',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Double Unders',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Regular Bounce',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Boxer Skip',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Run in Place',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
        ExerciseDetails(
          name: 'Jump Rope Double Unders',
          duration: Duration(seconds: 20),
          splitInterval: false,
          color: Colors.indigoAccent,
        ),
      ],
      colorSetRest: Colors.deepOrange,
      colorInterval: Colors.blueGrey,
      colorCountDown: Colors.teal,
      randomise: false,
      tabataStyle: false,
      vibrate: false,
      alertName: alertList[2],
    );
